### ISSUE TITLE
Gradle dependency does not work.

### ISSUE THREAD

**Issue by chinhhuynh** [soarcn/BottomSheet#104]
Hi,

I added the following line to build.gradle but was not able to resolve BottomSheet after syncing. External libraries does not show downloaded library for bottom sheet either. I'm using Android Studio. Am I missing something?

compile 'com.cocosw:bottomsheet:1.+@aar'

**Comment by soarcn** [comment]
Show us your build.gradle file please.

**Comment by rrbrambley** [comment]
Works for me.
