### ISSUE TITLE
Checkable Bottom Sheet

### ISSUE THREAD

**Issue by Gregliest** [soarcn/BottomSheet#107]
Hi,

What's the recommended way to show a checkable menu as a Bottom Sheet?  I've tried using the default as described [here](http://developer.android.com/guide/topics/ui/menus.html#checkable), and the radio buttons don't show up.  Thanks.

**Comment by stephenmcbride** [comment]
+1 would like to see this too! Thanks

**Comment by soarcn** [comment]
Sorry guys, no more new features.

**Comment by Gregliest** [comment]
Well, do you have any direction then on how we can hack around it, or could I submit a pull request?

**Comment by soarcn** [comment]
I suggest you could do it in your fork. 

- You need to change adapter and layout to consume checkable attribute.
- You need to add new interface to builder to user your own menu object (esp if you want to handle screen rotation)

And my personal view is, putting checkable item to model bottemsheet is not a good idea, they should be actions not states. You could ask UI designers' opinions where the option should put to.

Cheers

**Comment by Gregliest** [comment]
Great, thanks!
