### ISSUE TITLE
Attribute "bottomSheetStyle" has already been defined

### ISSUE THREAD

**Issue by stephenmcbride** [soarcn/BottomSheet#108]
The latest support library version (23.2.0) adds Google's own variety of BottomSheets and unfortunately there is name clash on the style attribute when you have both libraries as dependencies meaning the app fails to compile.

**Comment by soarcn** [comment]
Thanks, will fix soon

**Comment by Malachiasz** [comment]
I am waiting for this fix too

**Comment by caioyassoyama** [comment]
Fixed it. Pull request: https://github.com/soarcn/BottomSheet/pull/109

**Comment by soarcn** [comment]
@Malachiasz  good point, but in fact google's bottomsheet is a pattern or container, and this library is an out-of-box component, so there is no easy way to migrate from one to another. But I will find a time to create a demo using google's bottomsheet container.

**Comment by soarcn** [comment]
PR merged, new release is expected tomorrow.

**Comment by choumss** [comment]
Thanks for update :)

**Comment by Malachiasz** [comment]
@soarcn: if that is so, why do you stop work on this library? It seems not to loose it's reason to exist. Perhaps you could refactor it to use new support's library API, but IMHO it should be still supported.
(I have found this article about Google's Bottomsheer: https://medium.com/@nullthemall/new-bottomsheet-caab21aff19b )

**Comment by soarcn** [comment]
@Malachiasz  my plan is to create a reusable view allowing developer to put to google's bottomsheet. In such way, it's not fair to call it bottomsheet anymore. Anyway, for people who satisfy with the UI and functions provided, this library is far more convenient that google's.  I'm not saying I will stop working on it, but stop developing new features.

**Comment by Malachiasz** [comment]
Please release aar with bugfix. The lib is still unusable unless compiled from sources.

**Comment by caioyassoyama** [comment]
@Malachiasz Version 1.3.0 released and working.

**Comment by divyenduz** [comment]
Can you please put this in CHANGELOG also ?

**Comment by soarcn** [comment]
@divyenduz  good point, forgot to commit.

**Comment by stephenmcbride** [comment]
Thanks for fixing this @soarcn :)
