### ISSUE TITLE
please support vector drawable 

### ISSUE THREAD

**Issue by ahmadnajar10** [soarcn/BottomSheet#122]
please support vector drawable

**Comment by soarcn** [comment]
I use vector drawable with bottomsheet in my project, you might need other 3rd party libs to proceed your vector graphic to drawable object.  From library's point of view, it doesn't care the drawable is a bitmap or a vector. 

This is the method you could use once you get the drawable instance.
 public Builder sheet(int id, @NonNull Drawable icon, @NonNull CharSequence text)
