### ISSUE TITLE
make menu from Array of string

### ISSUE THREAD

**Issue by masooddalman** [soarcn/BottomSheet#123]
hi

it's good if this library can make sheet from array
something like this :

`
int[] ids={R.id.mid1,R.id.mid2,R.id.mid3,R.id.mid4};

String[] names={"item1","item2","item3","item4"};

new BottomSheet.Builder(context)
.title("TITLE")
.sheet(ids,names)
.show();
`

**Comment by soarcn** [comment]
Hi @masooddalman 
I don't think this would help to build a better readable code. The menu xml might be longer, but makes more sense.

I've no plan to add new interface to the implementation. You can create your own helper or do it in your own fork.

Thanks.
