### ISSUE TITLE
gradle build fail with android x and android.enableJetifier=true

### ISSUE THREAD

**Issue by iam1492** [soarcn/BottomSheet#142]
When I try migrate to Android X. Gradle build fail from bottomsheet library.
And gradle said I have to disable Jetifier option.

**Comment by KChernenko** [comment]
I have the same problem. Any workarounds?

**Comment by KChernenko** [comment]
As for now, you can use this fork:

`com.github.betterme-dev:BottomSheet:android-x-SNAPSHOT`

And add `matchingFallbacks = ['debug ']` and `matchingFallbacks = ['release']` for debug and release build types accordingly.

**Comment by mikehardy** [comment]
I think .buildscript/deploy_snapshot.sh needs to be altered or something? In order to deploy the aar without the AndroidManifest.xml in it?

**Comment by soarcn** [comment]
fixed in 1.5.0
