### ISSUE TITLE
Animation speed when showing

### ISSUE THREAD

**Issue by nole87** [soarcn/BottomSheet#143]
Hi,

On some phones when it shows it's really quick and on some it's normal. Is it possible to set animation duration? Thanks!

**Comment by soarcn** [comment]
Hi there,

you can define your own style and override the animation.  check out from example app

https://github.com/soarcn/BottomSheet/blob/master/example/src/main/res/values/styles.xml
<item name="android:windowAnimationStyle">@style/BottomSheet.Animation</item>
