### ISSUE TITLE
Orientation change looses dialog

### ISSUE THREAD

**Issue by pboos** [soarcn/BottomSheet#24]
Title says everything.

But don't bother yet. I think I will start working on this and send you a pull request. I think mainly it should be switched from Dialog to DialogFragment. That will require the support library. But I guess that is okay, right? Or both could be supported, but requires more work.

**Comment by soarcn** [comment]
Thanks @pboos ,  supporting dialogFragment is on the todo list, so it is great if you could provide a PR for this.

Refers to supporting both dialog or dialogfragment, my main concern is whether it could backward compatible with current interface and usage(at least most of them). If we could make it work, I prefer not supporting both of them, it would make it complex.

**Comment by soarcn** [comment]
And there is a tip for the users who might interest in the orientation changing problem. please check the example code to see how to correct show bottomsheet when configuration changed.

https://github.com/soarcn/BottomSheet/blob/master/example/src/main/java/com/cocosw/bottomsheet/example/ListAcitivty.java
