### ISSUE TITLE
Resource not found when building with Proguard

### ISSUE THREAD

**Issue by darkhunter25** [soarcn/BottomSheet#27]
I experience it on runtime. After I pressed the button that will run the show function it will crash with the exception resource not found..

It is working fine with no proguard. Can you help me set it up?

Thanks :)

**Comment by soarcn** [comment]
I use proguard in my project. It wouldn't have any problem, I didn't use reflection in this component, but if you enable shrinkResources , there might have an  issue that one anim resource(bs_list_layout_anim_in) will be removed.

Please show me your crash log, It is not hard to setup proguard config

**Comment by soarcn** [comment]
Seems Google has correct the shrinkResources issue.
I just add proguard support to example, you can check it as a reference.

**Comment by soarcn** [comment]
I will close this. Leave your comment if you have further issue about this.
