### ISSUE TITLE
IllegalStateException when using grid sheet

### ISSUE THREAD

**Issue by Mukul-Sharma** [soarcn/BottomSheet#28]
I ma getting this exception 
    java.lang.IllegalArgumentException
            at java.util.AbstractList.subList(AbstractList.java:736)
            at com.cocosw.bottomsheet.BottomSheet.init(BottomSheet.java:293)
            at com.cocosw.bottomsheet.BottomSheet.onCreate(BottomSheet.java:455)
            at android.app.Dialog.dispatchOnCreate(Dialog.java:361)
            at android.app.Dialog.show(Dialog.java:262)
            at com.cocosw.bottomsheet.BottomSheet$Builder.show(BottomSheet.java:733)

Only when i show-cancel repeatedly these steps 3-4 times and am using grid style sheet

**Comment by soarcn** [comment]
Hi @Mukul-Sharma Can you show me your code of calling bottomsheet, Can you reproduce this with sample application?

**Comment by Mukul-Sharma** [comment]
BottomSheetBuilder mBottomSheetBuilder = new BottomSheet.Builder(this).title(R.string.title_attachment_target).sheet(R.menu.attachment_target).listener(new DialogInterface.OnClickListener() {
            @Override
            public void onClick(DialogInterface dialogInterface, int i) {
                switch (i) {
                     //option cases
            }
        });
mBottomSheetBuilder.show();

**Comment by Mukul-Sharma** [comment]
One thing to note here is that what i was doing was store a BottomSheetBuilder reference, creating only one and then calling show on it whenever i needed to.
After creating new builder each time solved it for me

**Comment by soarcn** [comment]
I will check this. please don't keep builder reference, that would not save resources, you can keep a dialog reference to do so by using create()

**Comment by soarcn** [comment]
I've fixed this issue in master branch, you can please check it. But as I said, don't keep builder reference, it is meaningless.
