### ISSUE TITLE
is this possible

### ISSUE THREAD

**Issue by jjhesk** [soarcn/BottomSheet#29]
is this possible to draw down from the top??

**Comment by soarcn** [comment]
I don't quite understand your meaning. Do you mean changning the layout animation so the actions could appear from last one to first one?

**Comment by jjhesk** [comment]
not quite, I am trying to make the sheet to slide out from the top screen.

**Comment by soarcn** [comment]
You can customize the inAnimation, but bottomsheet will always stay at the bottom of the screen ( "Bottom"Sheet)
