### ISSUE TITLE
setCancelable(false) and setCanceledOnTouchOutside(false) doesn't work

### ISSUE THREAD

**Issue by bartwell** [soarcn/BottomSheet#36]
Hello!

Greate library, thank you!

Currently I need to create dialog which cannot be cloused by back button, swipe or touch outside. In my case it can be cloused only when user choose one of item on a sheet. But here is a problem: methods setCancelable(false) and setCanceledOnTouchOutside(false) doesn't work. Is there way to fix it? How to make sheet uncancelable?

**Comment by soarcn** [comment]
@bartwell 

BottomSheet should be cancelable according to specification, so it would override the cancelable setting. I will allow you to do this in next release, please help to verify it after I pull the update.

**Comment by bartwell** [comment]
@soarcn 

Thank you! I will verify it after update.

**Comment by bartwell** [comment]
Currently it working well. Thank you very much!
