### ISSUE TITLE
Bottom Sheet Form

### ISSUE THREAD

**Issue by samsoft00** [soarcn/BottomSheet#37]
Hello, Appreciate this great work, please is there a way to add Edittext to the bottom sheet and accept whatever user input???

**Comment by soarcn** [comment]
There is no plan to support custom layout yet, you can fork and implement it on your branch.

**Comment by samsoft00** [comment]
Alright, i will see to that this weekend but i will also like to ask if i can change the direction from bottom up to Up down?

**Comment by soarcn** [comment]
If you like to create an upside down bottomsheet, you need to change at least 3 parts.
1 change the gravity of dialog (BottomSheet.java 530)
2 change the in/out animation in the style
3 disable or change the swipe down to dismiss gesture (ClosableSlidingLayout.java)

If you need to compatible with translucent mode, there are far more work to do.
