### ISSUE TITLE
Error: java.lang.IllegalArgumentException: You should set icon for each items in grid style

### ISSUE THREAD

**Issue by brusasu** [soarcn/BottomSheet#49]
Hi, i added the library to gradle, copy/paste the style in my style.xml, added the menu in menu.xml, and on Main Class i added in the OnCreate() this snippet:
new BottomSheet.Builder(this).title("title").sheet(R.menu.list).listener(new DialogInterface.OnClickListener() {
                    @Override
                    public void onClick(DialogInterface dialog, int which) {
                        switch (which) {
                            case R.id.help:
                                Toast.makeText(getApplicationContext(), "test help menu", Toast.LENGTH_LONG).show();                                
                        break;
                        }
                    }
                }).show();

But AndroidStudio gives me this error: java.lang.IllegalArgumentException: You should set icon for each items in grid style.
Can you please help me to fix this error?

kind regards
Brus

**Comment by soarcn** [comment]
I can't reproduce this error right now. Can you send your test project to my mail? soarcn(at)gmail.com

**Comment by soarcn** [comment]
@brusasu  As the exception suggests, there are some of your menu items have no icon.

In your case, 
```xml
    <item android:id="@+id/action_settings" android:title="@string/action_settings"
        android:orderInCategory="100" app:showAsAction="never" />
```

**Comment by brusasu** [comment]
Fixed, great. 
Thanks for sharing this amazing library, and thanks for your help, i appreciated a lot.

Regards
Brus

**Comment by rohit101293** [comment]
public Builder sheet(int id, @DrawableRes int iconRes, @StringRes int textRes) {
            ActionMenuItem item = new ActionMenuItem(context, 0, id, 0, 0, context.getText(textRes));
            item.setIcon(iconRes);
            menu.add(item);
            return this;
        }


This line of your BottomSheet.java is throwing error. The items is not added as ActionMenuItem. It requires casting. Please provide a solution

**Comment by rohit101293** [comment]
And furthermore how to add those kind of icons as share in the last image like whatsapp facebook twitter
