### ISSUE TITLE
Make the Sheet scrollable

### ISSUE THREAD

**Issue by kashban** [soarcn/BottomSheet#5]
Currently when in Landscape mode the sheet quickly fills up the entire screen. Even worse, some action items are cut off. I could go to Grid mode, but on small screens even that won't help.

**Comment by marcusforsberg** [comment]
I still see the issue with some items being cut of near the bottom, for example in landscape mode when there's less space. Any news?

**Comment by soarcn** [comment]
@marcusforsberg Can you show me the screenshot?

**Comment by soarcn** [comment]
I just add a swiping up to open (more) actions in 0.8
