### ISSUE TITLE
Is there anyway that .sheet(---) method could take some Array list or so ?? Its hard to make a constant list as a menu xml file. 

### ISSUE THREAD

**Issue by pingothedoer** [soarcn/BottomSheet#50]

**Comment by soarcn** [comment]
Yes, I'm working on this. A menu inflator will be introduced for this.

**Comment by pingothedoer** [comment]
Ok...m definitely waiting for that.

**Comment by soarcn** [comment]
A huge update could be expected this weekend after my network setup getting done.

**Comment by pingothedoer** [comment]
That's really very cool

**Comment by soarcn** [comment]
I've updated master branch to 1.1.0 with the feature you need, but since this is an update with significant change, defects are expected, please help to test it before I push it to maven repository. Thanks.

**Comment by pingothedoer** [comment]
Thank you so much , i will definitely test it with several cases.

**Comment by pingothedoer** [comment]
sheet(int id, int iconRes, int textRes)
sheet(int id, @NonNull Drawable icon, @NonNull CharSequence text)
sheet(int id, int textRes)
sheet(int id, @NonNull CharSequence text)

All these methods are taking single item. how m i supposed to insert multiple items?

**Comment by pingothedoer** [comment]
Like i said in my question, what if i need to use some sort of collective data like arraylist or something instead of an xml menu file.

**Comment by soarcn** [comment]
@pingothedoer  you can get a Menu item from bottomsheet instance with getMenu(), it has standard android menu interface, you can do anything you want.

But, if what you needed is just insert multiple items, sheet() can do it quite well, just like the ShareAction in example application. I think this interface is simple enough with chain style programming, even simpler than arraylist.
