### ISSUE TITLE
Callback when click on CLOSE icon in Fullscreen mode

### ISSUE THREAD

**Issue by anticafe** [soarcn/BottomSheet#51]
In your demo app, I choose `FullScreen` section, then click on any name to invoke BottomSheet with ShareAction. I see click on `More...` in GridView will show BottomSheet in fullscreen mode with `bs_closeDrawable` (`X` sign) in the top left. We can touch on `bs_closeDrawable` to `showShortItems()` while press BACK will close BottomSheet.

Could you please provide callback when click on `bs_closeDrawable` ? I want to close BottomSheet instead of `showShortItems()`.

**Comment by soarcn** [comment]
This sounds odd to me, and against the ui specification. Any good reason why should do it like that way?  you can swipe down or press back to dismiss bottomsheet now.

**Comment by anticafe** [comment]
@soarcn CLOSE button (`bs_closeDrawable`) means close, therefore a normal user will assume touch on it will close BottomSheet.

**Comment by soarcn** [comment]
Ok, if the icon might confuse user is what you concern, you might override the icon to triangle. I could open a attribute for this. what do you think?

**Comment by anticafe** [comment]
Yes a triangle seems better :)

**Comment by soarcn** [comment]
Good, then you can define your own bottomsheet style with the drawable you want. I will keep current implementation for a while, and if there are more requests escalated about this, I could change it.
But you can please post your ideal icon to here for further change.
