### ISSUE TITLE
Option to disable menu options floating in animation

### ISSUE THREAD

**Issue by vemacs** [soarcn/BottomSheet#61]
Setting `windowAnimationStyle` to `@null` didn't seem to have any effect. I would like to disable the items in the bottom sheet "floating in" at different speeds without disabling the slide in animation on the bottom sheet, to match the Android Lollipop share intent animation and Google Drive's bottom sheet.

**Comment by soarcn** [comment]
You can override android:layoutAnimation, please check the sample application to know more about it

**Comment by vemacs** [comment]
```
    <style name="BottomSheet.StyleList" parent="BottomSheet.List.Dark" >
        <item name="android:listSelector">@drawable/list_selector</item>
        <item name="android:layoutAnimation">@null</item>
    </style>
```

Still displays the menu layout expand animation.

**Comment by vemacs** [comment]
In fact, I've deleted that anim file and set android:layoutAnimation to @null for everything, and still somehow get the menu expansion animation.

**Comment by soarcn** [comment]
@vemacs What's you done is correct, but it only affect "style" item, just check it out.

**Comment by vemacs** [comment]
@soarcn Sorry for being dumb, but I set it to `@null` for every single one of the styles and it still animates. Do you have any examples for the default layout XML to disable this?

**Comment by soarcn** [comment]
@vemacs You need to set bottomSheetStyle in your application/activity theme. If you do not know how to style application by using style.xml, you can please check google's document or you can show your application's styles.xml/manifest.xml here, and I could help you.
