### ISSUE TITLE
Can i change sheet item title after i selected it once?

### ISSUE THREAD

**Issue by gabrielaradu** [soarcn/BottomSheet#65]
Hello, I have this menu:
new BottomSheet.Builder(QuestionChatActivity.this)
						.title(getResources().getString(R.string.options))
						.sheet(R.menu.list)
						.listener(new DialogInterface.OnClickListener() {...}
                                               .show();
 In the listener part i added a switch to treat each option. Works great!
After i click one of the options, can i change the name or replace it with a new option?
Thanks.

**Comment by hofstede-matheus** [comment]
I had a simular problem, I wanted to change a image after a click, but the only workaround was using 2 different XML menu files. One referring to one image and the other to another. The menu XML is a int, so you can make a variable of it and change when you click the button. Hope it helps

**Comment by soarcn** [comment]
You can get MenuItem and change it as you like, no matter title, icon and status. Check sample for further info.
