### ISSUE TITLE
BottomSheet list title doesn't wrap text like Android 5.0 share intent

### ISSUE THREAD

**Issue by vemacs** [soarcn/BottomSheet#69]
Instead, the title is truncated with ... appended at the end. How could I change this behavior to fully wrap the text instead?

**Comment by soarcn** [comment]
You can customize it with
        <item name="bs_listStyle">@style/YOUR STYLE</item>

It's a simple textview, do whatever you want.

**Comment by jemshit** [comment]
How to use this ? can't apply custom theme. Any code would be helpful

**Comment by jemshit** [comment]
Can't make maxlines=2 for gridview text. I think we can not override it
