### ISSUE TITLE
Add a function for using an intent directly with the Builder

### ISSUE THREAD

**Issue by wmbest2** [soarcn/BottomSheet#72]
Currently you have an example of how an Intent can be used with the Builder to mimic the BottomSheet behavior on L+.  It would be nice if we could get a .intent() function on the builder itself to internalize this logic.

https://github.com/soarcn/BottomSheet/blob/master/example/src/main/java/com/cocosw/bottomsheet/example/ListAcitivty.java#L181

example:

~~~java
new BottomSheet.Builder(this)
    .intent(myShareIntent)
    .build();
~~~

**Comment by soarcn** [comment]
I'd love to keep the interface simple. I understand many people need this, I could create a separate helper class for this instead of make builder more complex.

**Comment by wmbest2** [comment]
That would work for me.  I wasn't sure why it was left out but I assumed it was purposeful; which is the reason I thought I would ask instead of implementing directly.
