### ISSUE TITLE
Shadow above the BottomSheet

### ISSUE THREAD

**Issue by azapps** [soarcn/BottomSheet#73]
It would be great to be able to add a small shadow above the BottomSheet. Sadly googles guidelines are not consistent about that:

Without shadow:
![without shadow](http://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bx4BSt6jniD7cWRoZDNiSzRZbm8/components_bottomsheets2.png)
With shadow:
![with shadow](http://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B6Okdz75tqQsQ2d5OV96aUVGR2c/components_bottomsheets_specs5.png)

**Comment by soarcn** [comment]
@azapps 

I'd like to keep current looking for now

But you can introduce shadow by overriding the following style

    <style name="BottomSheet.TopDivider">
        <item name="android:background">?bs_dividerColor</item>  <----- your shadow drawable
        <item name="android:layout_width">fill_parent</item>
        <item name="android:layout_height">1dp</item>
        <item name="android:layout_marginBottom">8dp</item>
    </style>
