### ISSUE TITLE
Cannot resolve BottomSheetHelper

### ISSUE THREAD

**Issue by KChernenko** [soarcn/BottomSheet#77]
Hi, I'm trying to implement share action like in the example:

```
private BottomSheet.Builder getShareActions(String text) {
        final Intent shareIntent = new Intent(Intent.ACTION_SEND);
        shareIntent.setType("text/plain");
        shareIntent.putExtra(Intent.EXTRA_TEXT, text);

        return BottomSheetHelper.shareAction(this, shareIntent);
    }
```
I've imported the library using gradle, but Android Studio couldn't find the `BottomSheetHelper` class.
![3](https://cloud.githubusercontent.com/assets/3322440/9021794/54dd74c6-385f-11e5-92f8-a1bda1491c33.PNG)

I've tried to clean and rebuild project, but nothing has changed.

**Comment by soarcn** [comment]
@KChernenko It's only available in master branch now, not yet push to maven repository yet.
and now what you can do:
- Wait for next release
- Copy Helper class to your project

**Comment by KChernenko** [comment]
@soarcn thanks)
