### ISSUE TITLE
Minimize instead of close sheet

### ISSUE THREAD

**Issue by IgorGanapolsky** [soarcn/BottomSheet#79]
Hi,
in your sample, when I view a **Style from Theme** sheet, sheets slide up correctly.  Then when I click **more**, the sheet slides up to full screen.  However, after that there is no way to minimize it back down to previous size.  Instead, it closes completely when I slide it down.

Please advise,
Igor

**Comment by soarcn** [comment]
@IgorGanapolsky 
You can click dismiss icon to minimize it to previous size (following material design specification)

**Comment by IgorGanapolsky** [comment]
But when I click dismiss ('X' at the top), or just swipe it down, it closes
the sheet completely.  I want it to minimize to previous position, NOT
close completely.

Are you seeing the same occurrence when running your code?

Igor

**Comment by soarcn** [comment]
It's working perfectly on my device, can you check it again with latest code?

**Comment by IgorGanapolsky** [comment]
Are you running the latest sample?

**Comment by soarcn** [comment]
Yes, can you send me your apk and video to my email?
