### ISSUE TITLE
Change icon onClick?!

### ISSUE THREAD

**Issue by MuhamedFathy** [soarcn/BottomSheet#81]
Is there anyway to change the icon of the sheets on item click?
Actually i tried but with no chance.
ex.
I want to make a `Favorite` option to favorite item and when i choose favorite i want the text and icon state to change to `Unfavorite`  and the icon changes too, is there anyway to do that?

**Comment by soarcn** [comment]
It's possible although I haven't confirm yet. you can get menu instance from bottomsheet instance and change it as you want.
But I don't think bottomsheet is designed for this scenario. you should consider fab/action menu

**Comment by MuhamedFathy** [comment]
Okay, thanks.
