### ISSUE TITLE
Allow access to ActionMenuItem or expose the groupId

### ISSUE THREAD

**Issue by KennyGoers** [soarcn/BottomSheet#83]
I need to make a menu with sections as is done with the menu resource, problem being is that it is dynamic and there is no way to break into sections with dynamic entries.

**Comment by harishrpatel** [comment]
Actually I had the opposite. I had two static menu items and rest I wanted to add programatically. When I get the Menu object and added MenuItems, it put a section break. I don't know if you are looking for sub menus. This method in Menu object has groupId. You can try with different groupIds.

    public MenuItem add(int groupId, int itemId, int order, CharSequence title);

**Comment by soarcn** [comment]
harishrpatel is right. You can get menu object, and do whatever you want.
