### ISSUE TITLE
BottomSheetHelper

### ISSUE THREAD

**Issue by marbat87** [soarcn/BottomSheet#84]
Hi,

I'm using version 1.1.1 of your library, but I cannot import BottomSheetHelper, althought it is a public class.

I added the dependency:
compile 'com.cocosw:bottomsheet:1.1.1@aar' (but I tried also with com.cocosw:bottomsheet:1.+@aar)

Is this issue just mine?

Thanks in advance

**Comment by soarcn** [comment]
#77
