### ISSUE TITLE
List with many items overlaps app bar

### ISSUE THREAD

**Issue by eric-sofisoftwarellc** [soarcn/BottomSheet#87]
If the number of items added to the sheet's list is large enough, the sheet becomes very tall. Material design says bottom sheets should not overlap the app bar. 

It looks like BottomSheet's top is determined by mStatusBarHeight which is inited to the height of the status bar; it'd be nice to be able to modify this, such as a setter to be able to customize the top.

**Comment by soarcn** [comment]
You can use limit(). Check fullscreen example for usage.

There's no problem to overlap app bar because this is a model bottomsheet

**Comment by eric-sofisoftwarellc** [comment]
limit() adds a more... option and once that is selected it goes full screen, so this isn't quite what we want from a usability standpoint (we'd prefer swipe to open). limit also doesn't take into account height of screen, so we're guessing what the limit should be. (A separate issue is it'd be nice to have the option of an "X" button to close the full screen layout).

Right now I'm doing this by overriding the layout and adding a android.support.percent.PercentRelativeLayout, which works ok.

**Comment by soarcn** [comment]
One easy way to do this is overriding TopDivider

    <style name="BottomSheet.TopDivider">
        <item name="android:background">?bs_dividerColor</item>
        <item name="android:layout_width">fill_parent</item>
        <item name="android:layout_height">1dp</item>
        <item name="android:layout_marginBottom">8dp</item>
        <item name="android:layout_marginTop">?actionBarSize</item>   <----  here
    </style>

or, you can have your own header layout

I would leave this to developer, because:
1   I don't( or hard) know if your activity have toolbar or not
2   I don't (or hard) know the height of your toolbar

One important reason that google suggest bottomsheet should not overlap appbar is that they want to close bottomsheet by clicking appbar icon, which is impossible with my implementation.

**Comment by eric-sofisoftwarellc** [comment]
A comment on overriding TopDivider, or using a header layout: tapping outside the bottom sheet should close it, and any kind of spacing like this that is inside the bottom sheet prevents that. I don't have a good solution for this yet.
