### ISSUE TITLE
Sort apps like youtube app

### ISSUE THREAD

**Issue by tuhin10** [soarcn/BottomSheet#89]
How can we list frequently used apps at the top with a divider just like youtube app ???

![screenshot_2015-09-26-18-05-35](https://cloud.githubusercontent.com/assets/11805182/10120095/250192be-64c9-11e5-974d-19384482124f.png)

**Comment by soarcn** [comment]
1  I might support grid mode with section in future release (when I have time)
2  You still need to provide the frequently used apps list by yourself (have no idea about this)
3  I would suggest you create an activity for this senario.

**Comment by soarcn** [comment]
Close this because no further development plan
