### ISSUE TITLE
API 19+ required for...

### ISSUE THREAD

**Issue by HakAl** [soarcn/BottomSheet#90]
the following method:
Could not find class 'android.transition.ChangeBounds', referenced from method com.cocosw.bottomsheet.BottomSheet.showFullItems

**Comment by soarcn** [comment]
If you wanna compile the project by yourself, you would need api 22+ sdk.
If you just need to use this library, use gradle, it will work on api 9+.

**Comment by HakAl** [comment]
I'm not trying to compile it myself. I'm telling you about a method that is called that shouldn't be. I'm describing an error displayed in logcat as a result of using this library. The method: com.cocosw.bottomsheet.BottomSheet.showFullItems uses: android.transition.ChangeBounds, which is only supported in API versions 19+. Just trying to help with a real issue, or find out why it's not.

**Comment by HakAl** [comment]
I just looked at the source and see you're calling it conditionally:
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
            Transition changeBounds = new ChangeBounds();
            changeBounds.setDuration(300);
            TransitionManager.beginDelayedTransition(list, changeBounds);
        }
I don't know why logcat complains.

**Comment by soarcn** [comment]
It will complain (always :) ), but won't affect you use it :) 
Thank you for letting me know :+1:
