### ISSUE TITLE
Item click listener no longer works after operating on items

### ISSUE THREAD

**Issue by scruffyfox** [soarcn/BottomSheet#91]
I have an xml menu resource with items I need to hide on certain conditions, calling `.build()` and then 
```
bottomSheet.getMenu().findItem(R.id.action_call).setVisible(false);
bottomSheet.invalidate();
```` 
for example, no longer calls the `DialogInterface.OnClickListener()` or `MenuItem.OnMenuItemClickListener()`, infact, none of the items are even clickable after calling that code

**Comment by Aqua-Ye** [comment]
I have the same issue.

**Comment by soarcn** [comment]
@scruffyfox Can you please provide a small demo for it. 
You can check the sample application to see how to hide/disable a item.

**Comment by sidlatau** [comment]
I also was facing same problem - it appears there is small bug in setVisible() method. I created pull request #98 with fix.

**Comment by soarcn** [comment]
pr been merged to master branch
