### ISSUE TITLE
Direction is not affected but locale configuration

### ISSUE THREAD

**Issue by CodeJjang** [soarcn/BottomSheet#94]
My androis locale language is RTL.
In all my activities in the app I set the locale to be English & LTR, and it works fine as all views are indeed LTR and text is English, except for the BottomSheet which for some reason sticks with the RTL configuration.

Any idea?

This is how I set locale:

    Resources res = activity.getResources();
    // Change locale settings in the app.
    DisplayMetrics dm = res.getDisplayMetrics();
    Configuration conf = res.getConfiguration();
    conf.locale = new Locale("en");
    res.updateConfiguration(conf, dm);
    
    // now set LTR as well
    int sdk = android.os.Build.VERSION.SDK_INT;
	if(sdk >= android.os.Build.VERSION_CODES.JELLY_BEAN_MR1){
	    activity.getWindow().getDecorView().setLayoutDirection(View.LAYOUT_DIRECTION_LTR);

**Comment by soarcn** [comment]
@CodeJjang  Can you try get the bottomsheet instance with build() and apply your code to bottomsheet. for example
``` code
bottomsheet.getWindow().getDecorView().setLayoutDirection(View.LAYOUT_DIRECTION_LTR);
```
I don't have environment to test it, please let me know if it not work.

**Comment by CodeJjang** [comment]
Works.
When I first .build(), then set LTR, and then call show(), it works.

**Comment by CodeJjang** [comment]
Damn. This solution worked for a grid layout, but doesn't work for the default linear one with a simple menu.
The menu items are still aligned to the right, while the title aligns itself to left.
