### ISSUE TITLE
When Bottom Sheet is shown, it blocks click action.

### ISSUE THREAD

**Issue by Isabek** [soarcn/BottomSheet#95]
I have an map activity. There are markers on map. And when user clicks marker I want to show Bottom Sheet.  It works fine. But, I have one problem. When I click marker it shows Bottom Sheet. And, I want click another marker. Unfortunately I can not. I should do double action. First, close the Bottom Sheet. Then click marker. Any ideas?

**Comment by soarcn** [comment]
Sorry you can't .Bottomsheet is a dialog, this library implements the materail design model bottomsheet pattern (https://www.google.com/design/spec/components/bottom-sheets.html) but not "Persistent Bottom Sheets"

I suggest you turn to AndroidSlidingUpPanel, https://github.com/umano/AndroidSlidingUpPanel
