### ISSUE TITLE
question: Is it possible to disable dim, and also be able to click above the bottom sheet?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [soarcn/BottomSheet#96]
as the title says.

**Comment by soarcn** [comment]
@AndroidDeveloperLB The answer is no. This library is dialog based .

**Comment by AndroidDeveloperLB** [comment]
Too bad :(
It's just that some Android apps do it, like Google Maps. I hoped for an alternative. 
Can you perhaps check this question on StackOverflow:
http://stackoverflow.com/q/34160423/878126

**Comment by soarcn** [comment]
You can use AndroidSlidingUpPanel  https://github.com/umano/AndroidSlidingUpPanel

**Comment by AndroidDeveloperLB** [comment]
For some reason, I couldn't import it:
https://github.com/umano/AndroidSlidingUpPanel/issues/621

**Comment by soarcn** [comment]
compile 'com.sothree.slidinguppanel:library:3.2.0'  should be fine

You don't need to change it for that purpose.

**Comment by AndroidDeveloperLB** [comment]
I don't understand. I've tried adding this line to the "dependencies" part of "AndroidSlidingUpPanel"'s gradle file, but it didn't help.
Even making it replace this line didn't help:

    compile project(':library')

**Comment by AndroidDeveloperLB** [comment]
ok, found a way to fix the building errors but now I have a crash:
https://github.com/umano/AndroidSlidingUpPanel/issues/621
