### ISSUE TITLE
Question: is it possible to make the content scroll till it cover the whole screen?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [soarcn/BottomSheet#97]
And then even scroll more if the content has a scrolling view?
Maybe even have a CollapsingToolbarLayout ?

**Comment by soarcn** [comment]
No plan to do this.

**Comment by AndroidDeveloperLB** [comment]
Too bad. That's how it works on the material design guidelines:
https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bzhp5Z4wHba3YXA2Y3RoSnhPM2c/components_bottomsheets_modal6.png

taken from:
https://www.google.com/design/spec/components/bottom-sheets.html#bottom-sheets-modal-bottom-sheets

**Comment by soarcn** [comment]
Because this library is dialog based model view,  the sample you provide is a Persistent Bottom Sheets.
You can turn to flipboard's bottomsheet for that purpose.

**Comment by AndroidDeveloperLB** [comment]
@soarcn I know, but it has its own issues there :(

**Comment by soarcn** [comment]
@AndroidDeveloperLB  Googler said they have plan of offical bottomsheet, so I decided not to rewrite a view based bottomsheet.  Model Bottom Sheet is the boundry of this library.

**Comment by AndroidDeveloperLB** [comment]
@soarcn Yes, they said it, but it was promised quite a long time ago, and I was assigned to use bottom sheet, so I can't use something that doesn't exist yet.

**Comment by soarcn** [comment]
I reckon you need to fork flipboard's bottomsheet can modify it for your own purpose :)

**Comment by AndroidDeveloperLB** [comment]
@soarcn I already did, kinda :
https://github.com/AndroidDeveloperLB/ThreePhasesBottomSheet
I wish to fix there some bugs, and make it look a bit nicer.
